[build]
nixpacks = true

[deploy]
numReplicas = 1

[nixpacks]
pkgs = [
  "ffmpeg",
  "libgcc",
  "libglib",
  "libglvnd",
  "libglvnd.dev",
  "libsm6",
  "libxrender",
  "libxext",
  "libstdc++",
  "libxcb",
  "mesa",
  "mesa-dev"
]

[variables]
PORT = "8080"
